build:
  maxIssues: 10

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

complexity:
  LongParameterList:
    functionThreshold: 10
    ignoreDefaultParameters: true
    excludes:
      - '**/*ViewModel.kt'
  TooManyFunctions:
    active: false
  LongMethod:
    threshold: 80
    
style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
  UnusedImports:
    active: true
  ForbiddenComment:
    active: false
  WildcardImport: 
    excludeImports: ['org.junit.Assert.*']

exceptions:
  TooGenericExceptionCaught:
    active: false
